instance:
  _target_: teleoperation.camera.camera_multi_oak.CameraMultiOak
  keys:
    top: ???
    waist: ???
  camera_config:
    fps: 30
    width: 1280
    height: 800
    use_depth: ${use_depth}
    resolution: "800p"

  display_config:
    key: "top"
    mode: "mono"
    resolution: "400p"
    crop_sizes: [0, 0, 0, 0]

  save_processes: 6
  save_threads: 12
  save_queue_size: 120
