[project]
name = "teleoperation"
version = "0.6.1"
description = "Teleoperation for Fourier Robots"
authors = [{ name = "Yuxiang Gao", email = "yuxiang.gao@fftai.com" }]
dependencies = [
    "numpy>=2.0.0",
    "h5py>=3.11.0",
    "vuer[all]==0.0.32rc8",
    "tqdm>=4.66.5",
    "rich>=13.8.1",
    "opencv-python>=4.10.0.84",
    "opencv-contrib-python>=4.10.0.84",
    "pynput>=1.7.7,<1.8.0",
    "omegaconf>=2.3.0",
    "dex-retargeting<0.5.0",
    "pin-pink>=3.3.0",
    "qpsolvers[daqp,clarabel]>=4.6.0",
    "rerun-sdk==0.22.1",
    "meshcat>=0.3.2",
    "meshcat-shapes>=0.3.0",
    "numba>=0.60.0",
    "pillow>=11.0.0",
    "hydra-core>=1.3.2",
    "hydra-colorlog>=1.2.0",
    "filelock>=3.16.1",
    "zmq>=0.0.0",
    "fourier-robot-descriptions",
    "evdev>=1.9.2",
    # "dexhandpy==0.0.42"
]
requires-python = "~=3.10,<3.12"
readme = "README.md"
license = { text = "MIT" }


[project.optional-dependencies]
webrtc = [
    "aiohttp>=3.10.5",
    "aiohttp-cors>=0.7.0",
    "aiortc>=0.9.8",
    "av>=12.3.0",
]
realsense = ["pyrealsense2>=2.55.1.6486"]
depthai = ["depthai-sdk>=1.15.0", "av>=13.1.0"]
cpu = ["torch==2.5.1", "torchvision==0.20.1"]
gpu = ["torch>=2.5.1", "torchvision>=0.20.1"]
lerobot = ["torch==2.6.0", "torchvision>=0.21.0"] # TODO: document this
# lerobot = ["lerobot[flash-attn]", "torch==2.6.0", "torchvision>=0.21.0"]
# lerobot = ["lerobot", "torch==2.6.0", "torchvision>=0.21.0"]
# fourier = ["fourier-grx-client==0.2.0a8", "fourier-dhx>=0.0.2"]
# lerobot = ["lerobot[pi0]"]

[tool.uv]
package = true
default-groups = ["dev", "fourier"]
conflicts = [[{ extra = "cpu" }, { extra = "gpu" }, { extra = "lerobot" }]]

[tool.uv.sources]
torch = [
    { index = "torch-cpu", extra = "cpu" },
    { index = "torch-gpu", extra = "gpu" },
    { index = "torch-gpu", extra = "lerobot" },

]
torchvision = [
    { index = "torch-cpu", extra = "cpu" },
    { index = "torch-gpu", extra = "gpu" },
    { index = "torch-gpu", extra = "lerobot" },
]
fourier-robot-descriptions = { git = "https://github.com/yuxiang-gao/fourier-robot-descriptions.git", rev = "dabc035de0aef33e4d079cf46e0e2ee7583837d8" }
# fourier-robot-descriptions = { path = "../fourier-robot-descriptions.py", editable = true }
# dexhandpy = { index = "internal" }
depthai_sdk = { git="https://github.com/yuxiang-gao/depthai.git", branch = "main", subdirectory = "depthai_sdk" }
# dexhandpy = { path = "dexhandpy-0.0.42-cp310-cp310-linux_x86_64.whl" }
# lerobot = { path = "../fourier-lerobot", editable = true }
# lerobot = { git = "https://github.com/huggingface/lerobot.git" }

[[tool.uv.index]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[[tool.uv.index]]
name = "torch-cpu"
url = "https://mirror.sjtu.edu.cn/pytorch-wheels/cpu"
explicit = true

[[tool.uv.index]]
name = "torch-gpu"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[[tool.uv.index]]
name = "test"
url = "https://test.pypi.org/simple"
explicit = true

# [[tool.uv.index]]
# name = "internal"
# url = "http://192.168.3.35:8088/repository/pypi/simple "
# explicit = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
include = ["**/*.py", "**/*.pyi", "**/pyproject.toml"]
exclude = [".venv", "build", "dist", "scripts", "src/teleoperation/webrtc"]
line-length = 120

[tool.ruff.lint]
select = [
    "A",   # flake8-builtins
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "E",   # pycodestyle - Error
    "W",   # pycodestyle - Warning
    "F",   # Pyflakes
    'PLC',
    'PLE',
    'PLW', # Pylint
    "I",   # isort
    "UP",  # pyupgrade
    "NPY", # numpy
]
ignore = [
    "E501", # line-too-long
    # "F401", # unused import
    "F841", # unused variable,
    "E741", # ambiguous variable name
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.isort]
known-first-party = ["teleoperation"]


[tool.pyright]
include = ["src/**/*.py"]
pythonVersion = "3.11"
pythonPlatform = "Linux"

[tool.ruff.lint.pydocstyle]
convention = "google"

[project.scripts]
teleoperation = "teleoperation.main:main"


[dependency-groups]
dev = [
    "markdown-exec>=1.10.0",
    "mike>=2.1.3",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.5.49",
    "mkdocstrings[python]>=0.27.0",
    "pre-commit>=4.0.1",
    "pyright>=1.1.391",
    "pytest>=8.3.4",
    "ruff>=0.9.1",
]
fourier = [
    "fourier-grx-client==0.2.0a8",
    "fourier-grx-dds==0.2.7a0",
    "fourier-dhx>=0.0.2",
    "pybind11>=2.13.6",
    # "dexhandpy==0.0.37",
    # "dexhandpy==0.0.42",
]
