instance:
  _target_: teleoperation.adapter.robots.grx_dds.GR1Robot
  dds_cfg: "${robot.dds_config}"
  controlled_joint_indices: "${robot.controlled_joint_indices}"
  default_qpos: "${robot.default_qpos}"
  named_links: "${robot.named_links}"
  target_hz: "${upsampler.frequency}"

dds_domain_id: ???
dds_namespace: "/farts/gr2"
urdf_path: "urdf/GR2T2_fourier_hand_6dof.urdf"
urdf_package_dirs: ["urdf"]

controlled_joint_indices: "${eval:'list(range(12, 29))'}"
default_qpos: "${eval:'np.array([
  0.0, 0.0, 0.0,
  -np.pi / 12, 0.1, 0, -np.pi / 2, 0, 0, 0,
  -np.pi / 12, -0.1, 0, -np.pi / 2, 0, 0, 0])'}"
num_joints: 29
joint_names:
  [
    "left_hip_pitch_joint",
    "left_hip_roll_joint",
    "left_hip_yaw_joint",
    "left_knee_pitch_joint",
    "left_ankle_roll_joint",
    "left_ankle_pitch_joint",
    "right_hip_pitch_joint",
    "right_hip_roll_joint",
    "right_hip_yaw_joint",
    "right_knee_pitch_joint",
    "right_ankle_roll_joint",
    "right_ankle_pitch_joint",
    "waist_yaw_joint",
    "head_yaw_joint",
    "head_pitch_joint",
    "left_shoulder_pitch_joint",
    "left_shoulder_roll_joint",
    "left_shoulder_yaw_joint",
    "left_elbow_pitch_joint",
    "left_wrist_yaw_joint",
    "left_wrist_pitch_joint",
    "left_wrist_roll_joint",
    "right_shoulder_pitch_joint",
    "right_shoulder_roll_joint",
    "right_shoulder_yaw_joint",
    "right_elbow_pitch_joint",
    "right_wrist_yaw_joint",
    "right_wrist_pitch_joint",
    "right_wrist_roll_joint",
  ]

visualize: false
debug: ${debug}
debug_hand: ${debug_hand}
display_collisions: false
displayed_frames:
  # - "right_ee_frame"
  # - "left_ee_frame"
  # - "R_hand_base_link"
  # - "L_hand_base_link"
  - "base_link"
  - "torso_link"
  - "head_pitch_link"
  - "left_end_effector_link"
  - "right_end_effector_link"

self_collision:
  enable: false
  min_distance: 0.02
  enabled_links: ["right_hand_yaw_link", "left_hand_yaw_link", "torso_link"]

joints_to_lock: []

waist_joints: ["waist_yaw_joint"]
head_joints: ["head_yaw_joint", "head_pitch_joint"]

# frames:
#   - name: "right_end_effector_link"
#     parent: "right_hand_roll_link"
#   - name: "left_end_effector_link"
#     parent: "left_hand_roll_link"

joint_limits:
  left_shoulder_pitch_joint: [-2.27, 0.7]
  right_shoulder_pitch_joint: [-2.27, 0.7]

  left_shoulder_roll_joint: [-0.1, 1.57]
  right_shoulder_roll_joint: [-1.57, 0.1]

  # left_shoulder_yaw_joint: [-1.67, 1.67]
  # right_shoulder_yaw_joint: [-1.67, 1.67]

  # left_elbow_pitch_joint: [-2.27, 0.3]
  # right_elbow_pitch_joint: [-2.27, 0.3]

  # waist_yaw_joint: [-0.5, 0.5]

  # left_wrist_pitch_joint: [-0.6, 0.6]
  # left_wrist_roll_joint: [-0.87, 0.87]

  # right_wrist_pitch_joint: [-0.6, 0.6]
  # right_wrist_roll_joint: [-0.87, 0.87]

velocity_limits:
  waist_yaw_joint: 1.0
  waist_pitch_joint: 0.3
  head_pitch_joint: 1.0
  head_yaw_joint: 1.0
  left_shoulder_roll_joint: 6.283185307179586
  left_shoulder_pitch_joint: 6.283185307179586
  left_shoulder_yaw_joint: 6.283185307179586
  left_elbow_pitch_joint: 6.283185307179586
  left_wrist_yaw_joint: 6.283185307179586
  left_wrist_pitch_joint: 6.283185307179586
  left_wrist_roll_joint: 6.283185307179586
  right_shoulder_roll_joint: 6.283185307179586
  right_shoulder_pitch_joint: 6.283185307179586
  right_shoulder_yaw_joint: 6.283185307179586
  right_elbow_pitch_joint: 6.283185307179586
  right_wrist_yaw_joint: 6.283185307179586
  right_wrist_pitch_joint: 6.283185307179586
  right_wrist_roll_joint: 6.283185307179586

body_scaling_factor: 1.15

position_filter:
  min_cutoff: 0.01
  beta: 1.0

orientation_filter:
  alpha: 0.6

named_links:
  root_link: "base_link"
  left_end_effector_link: "left_end_effector_link"
  right_end_effector_link: "right_end_effector_link"
  head_link: "head_pitch_link"
  # left_elbow_pitch_joint: "left_elbow_pitch_joint"
  # right_elbow_pitch_joint: "right_elbow_pitch_joint"

calibration_pose:
  left_elbow_pitch_joint: "${eval:'-np.pi / 2'}"
  right_elbow_pitch_joint: "${eval:'-np.pi / 2'}"

dds_config:
  domain_id: "${robot.dds_domain_id}"
  encoders_state_path: "server_config/dds/encoders_state.yaml"
  motor_gains_path: "server_config/dds/motor_gains.yaml"
  topic_prefix: "${robot.dds_namespace}"
  frequency: 100
  use_imu: false
  robot: gr2t5
  disabled_pose_solver: ["ankle", "wrist", "head"] # For gr2t5, all joints are serial chains

  # Kinematics configuration
  urdf_path: "assets/urdf/GR2T2_fourier_hand_6dof.urdf"
  urdf_package_dirs: ["assets/urdf"]
  self_collision:
    enable: false
    min_distance: 0.02
    enabled_links: ["right_hand_yaw_link", "left_hand_yaw_link", "torso_link"]
  visualize: false
  debug: false
  ee_link:
    head: "head_yaw_link"
    left_arm: "left_end_effector_link"
    right_arm: "right_end_effector_link"
  display_collisions: false
  displayed_frames:
    - "r_hand_base_link"
    - "l_hand_base_link"
    - "base_link"
    - "torso_link"
    - "head_yaw_link"
  named_links:
    root_link: "base_link"
    left_end_effector_link: "left_end_effector_link"
    right_end_effector_link: "right_end_effector_link"
    head_link: "head_yaw_link"
    left_elbow_pitch_joint: "left_elbow_pitch_joint"
    right_elbow_pitch_joint: "right_elbow_pitch_joint"
  joints_to_lock: ["waist_yaw_joint"] # Locked joints will not involve in the kinematic chain

  # Gravity compensation
  target_hz: "${upsampler.frequency}"
  impedance_controller:
    k:
      [
        60.0,
        15.0,
        15.0,
        60.0,
        70.0,
        70.0,
        60.0,
        15.0,
        15.0,
        15.0,
        60.0,
        70.0,
        70.0,
        60.0,
        15.0,
        15.0,
        15.0,
      ]
    b:
      [
        5.0,
        1.0,
        1.0,
        5.0,
        5.0,
        5.0,
        5.0,
        1.0,
        1.0,
        1.0,
        5.0,
        5.0,
        5.0,
        5.0,
        1.0,
        1.0,
        1.0,
      ]
    m:
      [
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
      ]
    max_effort:
      [
        50.0,
        50.0,
        50.0,
        50.0,
        50.0,
        50.0,
        50.0,
        50.0,
        50.0,
        50.0,
        50.0,
        50.0,
        50.0,
        50.0,
        50.0,
        50.0,
        50.0,
      ]
  # Joint configuration
  joints:
    left_hip_roll_joint:
      enable: false
      direction: -1
      initialization_pose_degree: 0
      min_pose_degree: -5.156620156177409
      max_pose_degree: 45.26366581533504
      reduction_ratio: 31
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 3.751
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: 0
      actuator_type: FSA_TYPE_802030
    left_hip_yaw_joint:
      enable: false
      direction: 1
      initialization_pose_degree: 0
      min_pose_degree: -40.10704565915762
      max_pose_degree: 40.10704565915762
      reduction_ratio: 51
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 3.4170000000000003
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: 0
      actuator_type: FSA_TYPE_601750
    left_hip_pitch_joint:
      enable: false
      direction: 1
      initialization_pose_degree: 0
      min_pose_degree: -100.26761414789407
      max_pose_degree: 40.10704565915762
      reduction_ratio: 7
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 1.82
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: -15.000033378601074
      actuator_type: FSA_TYPE_1307E
    left_knee_pitch_joint:
      enable: false
      direction: -1
      initialization_pose_degree: 0
      min_pose_degree: -5.156620156177409
      max_pose_degree: 110.00789666511805
      reduction_ratio: 7
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 1.82
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: 30.00006675720215
      actuator_type: FSA_TYPE_1307E
    left_ankle_pitch_joint:
      enable: false
      direction: -1
      initialization_pose_degree: 0
      min_pose_degree: -60.16056848873644
      max_pose_degree: 29.79380534680281
      reduction_ratio: 36
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 2.16
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: -15.000033378601074
      actuator_type: FSA_TYPE_36B36E
    left_ankle_roll_joint:
      enable: false
      direction: 1
      initialization_pose_degree: 0
      min_pose_degree: -25.210142985756224
      max_pose_degree: 25.210142985756224
      reduction_ratio: 36
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 2.16
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: 0
      actuator_type: FSA_TYPE_36B36E
    right_hip_roll_joint:
      enable: false
      direction: -1
      initialization_pose_degree: 0
      min_pose_degree: -5.156620156177409
      max_pose_degree: 5.156620156177409
      reduction_ratio: 31
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 3.751
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: 0
      actuator_type: FSA_TYPE_802030
    right_hip_yaw_joint:
      enable: false
      direction: 1
      initialization_pose_degree: 0
      min_pose_degree: -40.10704565915762
      max_pose_degree: 40.10704565915762
      reduction_ratio: 51
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 3.4170000000000003
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: 0
      actuator_type: FSA_TYPE_601750
    right_hip_pitch_joint:
      enable: false
      direction: -1
      initialization_pose_degree: 0
      min_pose_degree: -100.26761414789407
      max_pose_degree: 40.10704565915762
      reduction_ratio: 7
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 1.82
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: -15.000033378601074
      actuator_type: FSA_TYPE_1307E
    right_knee_pitch_joint:
      enable: false
      direction: 1
      initialization_pose_degree: 0
      min_pose_degree: -5.156620156177409
      max_pose_degree: 110.00789666511805
      reduction_ratio: 7
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 1.82
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: 30.00006675720215
      actuator_type: FSA_TYPE_1307E
    right_ankle_pitch_joint:
      enable: false
      direction: 1
      initialization_pose_degree: 0
      min_pose_degree: -60.16056848873644
      max_pose_degree: 29.79380534680281
      reduction_ratio: 36
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 2.16
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: -15.000033378601074
      actuator_type: FSA_TYPE_36B36E
    right_ankle_roll_joint:
      enable: false
      direction: -1
      initialization_pose_degree: 0
      min_pose_degree: -25.210142985756224
      max_pose_degree: 25.210142985756224
      reduction_ratio: 36
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 2.16
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: 0
      actuator_type: FSA_TYPE_36B36E
    waist_yaw_joint:
      enable: false
      direction: -1
      initialization_pose_degree: 0
      min_pose_degree: -60.16056848873644
      max_pose_degree: 60.16056848873644
      reduction_ratio: 51
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 3.4170000000000003
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: 0
      actuator_type: FSA_TYPE_601750
    head_yaw_joint:
      enable: true
      direction: -1
      initialization_pose_degree: 0
      min_pose_degree: -29.79380534680281
      max_pose_degree: 20.05352282957881
      reduction_ratio: 51
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 3.06
      position_kp: 0.0
      velocity_kp: 0.0
      mode: None
      default_pose_degree: 0
      actuator_type: FSA_TYPE_250830
    head_pitch_joint:
      enable: true
      direction: 1
      initialization_pose_degree: 0
      min_pose_degree: -155.2715624804531
      max_pose_degree: 155.2715624804531
      reduction_ratio: 51
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 3.06
      position_kp: 0.0
      velocity_kp: 0.0
      mode: None
      default_pose_degree: 0
      actuator_type: FSA_TYPE_250830
    left_shoulder_pitch_joint:
      enable: true
      direction: -1
      initialization_pose_degree: 0
      min_pose_degree: -159.85522484149968
      max_pose_degree: 110.00789666511805
      reduction_ratio: 80
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 4.8
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: 0
      actuator_type: FSA_TYPE_361480
    left_shoulder_roll_joint:
      enable: true
      direction: -1
      initialization_pose_degree: 0
      min_pose_degree: -32.65859432245692
      max_pose_degree: 187.3571990077792
      reduction_ratio: 80
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 4.8
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: 0
      actuator_type: FSA_TYPE_361480
    left_shoulder_yaw_joint:
      enable: true
      direction: 1
      initialization_pose_degree: 0
      min_pose_degree: -170.1684651538545
      max_pose_degree: 170.1684651538545
      reduction_ratio: 100
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 6
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: 0
      actuator_type: FSA_TYPE_3611100
    left_elbow_pitch_joint:
      enable: true
      direction: -1
      initialization_pose_degree: 0
      min_pose_degree: -130.06141949469688
      max_pose_degree: 130.06141949469688
      reduction_ratio: 100
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 6
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: -17.18873405456543
      actuator_type: FSA_TYPE_3611100
    left_wrist_yaw_joint:
      enable: true
      direction: 1
      initialization_pose_degree: 0
      min_pose_degree: -170.1684651538545
      max_pose_degree: 170.1684651538545
      reduction_ratio: 31
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 1.8599999999999999
      position_kp: 0.0
      velocity_kp: 0.0
      mode: None
      default_pose_degree: 0
      actuator_type: FSA_TYPE_3611100
    left_wrist_pitch_joint:
      enable: true
      direction: -1
      initialization_pose_degree: 0
      min_pose_degree: -34.95042550298022
      max_pose_degree: 34.95042550298022
      reduction_ratio: 31
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 1.8599999999999999
      position_kp: 0.0
      velocity_kp: 0.0
      mode: None
      default_pose_degree: 0
      actuator_type: FSA_TYPE_250830
    left_wrist_roll_joint:
      enable: true
      direction: -1
      initialization_pose_degree: 0
      min_pose_degree: -50.0
      max_pose_degree: 50.0
      reduction_ratio: 31
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 1.8599999999999999
      position_kp: 0.0
      velocity_kp: 0.0
      mode: None
      default_pose_degree: 0
      actuator_type: FSA_TYPE_250830
    right_shoulder_pitch_joint:
      enable: true
      direction: 1
      initialization_pose_degree: 0
      min_pose_degree: -159.85522484149968
      max_pose_degree: 110.00789666511805
      reduction_ratio: 80
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 4.8
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: 0
      actuator_type: FSA_TYPE_361480
    right_shoulder_roll_joint:
      enable: true
      direction: -1
      initialization_pose_degree: 0
      min_pose_degree: -32.65859432245692
      max_pose_degree: 32.65859432245692
      reduction_ratio: 80
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 4.8
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: 0
      actuator_type: FSA_TYPE_361480
    right_shoulder_yaw_joint:
      enable: true
      direction: 1
      initialization_pose_degree: 0
      min_pose_degree: -170.1684651538545
      max_pose_degree: 170.1684651538545
      reduction_ratio: 100
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 6
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: 0
      actuator_type: FSA_TYPE_3611100
    right_elbow_pitch_joint:
      enable: true
      direction: 1
      initialization_pose_degree: 0
      min_pose_degree: -130.06141949469688
      max_pose_degree: 130.06141949469688
      reduction_ratio: 100
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 6
      position_kp: 0.0
      velocity_kp: 0.0
      mode: PD
      default_pose_degree: -17.18873405456543
      actuator_type: FSA_TYPE_3611100
    right_wrist_yaw_joint:
      enable: true
      direction: 1
      initialization_pose_degree: 0
      min_pose_degree: -170.1684651538545
      max_pose_degree: 170.1684651538545
      reduction_ratio: 31
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 1.8599999999999999
      position_kp: 0.0
      velocity_kp: 0.0
      mode: None
      default_pose_degree: 0
      actuator_type: FSA_TYPE_3611100
    right_wrist_pitch_joint:
      enable: true
      direction: 1
      initialization_pose_degree: 0
      min_pose_degree: -34.95042550298022
      max_pose_degree: 34.95042550298022
      reduction_ratio: 31
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 1.8599999999999999
      position_kp: 0.0
      velocity_kp: 0.0
      mode: None
      default_pose_degree: 0
      actuator_type: FSA_TYPE_250830
    right_wrist_roll_joint:
      enable: true
      direction: -1
      initialization_pose_degree: 0
      min_pose_degree: -50.0
      max_pose_degree: 50.0
      reduction_ratio: 31
      kinematic_reduction_ratio: 1
      kinetic_reduction_ratio: 1.8599999999999999
      position_kp: 0.0
      velocity_kp: 0.0
      mode: None
      default_pose_degree: 0
      actuator_type: FSA_TYPE_250830

  imu: Body/IMU
