instance:
  _target_: teleoperation.policy.lerobot.LerobotPolicy
  repo_id: "FourierIntelligence/pick-lemon-200-256x256"
  type: "act"
  pretrained_path: ???

  policy_config:
    chunk_size: 100
    n_action_steps: 24
    dim_model: 512
    vision_backbone: dino_v2
