type: "fourier"

left_hand:
  _target_: teleoperation.adapter.hands.fourier.FourierDexHand
  hand_ip: "192.168.137.19"

right_hand:
  _target_: teleoperation.adapter.hands.fourier.FourierDexHand
  hand_ip: "192.168.137.39"

prefix_left: "L_"
prefix_right: "R_"

tip_indices: [4, 9, 14, 19, 24]
actuated_indices: [0, 2, 6, 4, 9, 8]
range_max: [10.3, 10.3, 10.3, 10.3, 0.0, 10.3]
range_min: [0.0, 0.0, 0.0, 0.0, 10.3, 0.0]

left:
  type: vector
  urdf_path: urdf/fourier_left_hand_6dof.urdf
  wrist_link_name: "L_hand_base_link"

  # Target refers to the retargeting target, which is the robot hand
  # target_joint_names: null
  target_origin_link_names:
    [
      "L_hand_base_link",
      "L_hand_base_link",
      "L_hand_base_link",
      "L_hand_base_link",
      "L_hand_base_link",
    ]
  target_task_link_names:
    [
      "L_thumb_tip_link",
      "L_index_tip_link",
      "L_middle_tip_link",
      "L_ring_tip_link",
      "L_pinky_tip_link",
    ]

  target_joint_names:
    [
      "L_pinky_proximal_joint",
      "L_ring_proximal_joint",
      "L_middle_proximal_joint",
      "L_index_proximal_joint",
      "L_thumb_proximal_pitch_joint",
      "L_thumb_proximal_yaw_joint",
    ]
  # finger_tip_link_names: [ "thumb_tip",  "index_tip", "middle_tip", "ring_tip", "pinky_tip" ]
  scaling_factor: 0.95

  # Source refers to the retargeting input, which usually corresponds to the human hand
  # The joint indices of human hand joint which corresponds to each link in the target_link_names
  target_link_human_indices: [[0, 0, 0, 0, 0], [4, 9, 14, 19, 24]]
  # target_link_human_indices: [[0, 0, 0, 0, 0], [4, 8, 12, 16, 20]]

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  low_pass_alpha: 0.5

right:
  type: vector
  urdf_path: urdf/fourier_right_hand_6dof.urdf
  # urdf_path: gr1_inspire/urdf/T2-dex.urdf
  wrist_link_name: "R_hand_base_link"

  # Target refers to the retargeting target, which is the robot hand
  # target_joint_names: null
  target_origin_link_names:
    [
      "R_hand_base_link",
      "R_hand_base_link",
      "R_hand_base_link",
      "R_hand_base_link",
      "R_hand_base_link",
    ]
  target_task_link_names:
    [
      "R_thumb_tip_link",
      "R_index_tip_link",
      "R_middle_tip_link",
      "R_ring_tip_link",
      "R_pinky_tip_link",
    ]
  target_joint_names:
    [
      "R_pinky_proximal_joint",
      "R_ring_proximal_joint",
      "R_middle_proximal_joint",
      "R_index_proximal_joint",
      "R_thumb_proximal_pitch_joint",
      "R_thumb_proximal_yaw_joint",
    ]
  # finger_tip_link_names: [ "thumb_tip",  "index_tip", "middle_tip", "ring_tip", "pinky_tip" ]
  scaling_factor: 0.95

  # Source refers to the retargeting input, which usually corresponds to the human hand
  # The joint indices of human hand joint which corresponds to each link in the target_link_names
  target_link_human_indices: [[0, 0, 0, 0, 0], [4, 9, 14, 19, 24]]

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  low_pass_alpha: 0.5
