type: "inspire"

left_hand:
  _target_: teleohand.hands.inspire.InspireDexHand
  ip: "192.168.137.19"

right_hand:
  _target_: teleohand.hands.inspire.InspireDexHand
  ip: "192.168.137.39"

prefix_left: "L_"
prefix_right: "R_"

tip_indices: [4, 9, 14, 19, 24]
actuated_indices: [4, 6, 2, 0, 9, 8]
range_max: [1000, 1000, 1000, 1000, 1000, 1000]
range_min: [0, 0, 0, 0, 0, 0]


left:
  type: DexPilot
  urdf_path: urdf/inspire_left_hand.urdf
  wrist_link_name: "L_hand_base_link"

  finger_tip_link_names:
    ["L_thumb_tip", "L_index_tip", "L_middle_tip", "L_ring_tip", "L_pinky_tip"]


  target_joint_names:
    [
      "L_pinky_proximal_joint",
      "L_ring_proximal_joint",
      "L_middle_proximal_joint",
      "L_index_proximal_joint",
      "L_thumb_proximal_pitch_joint",
      "L_thumb_proximal_yaw_joint",
    ]
  scaling_factor: 0.85
  # target_link_human_indices: [[0, 0, 0, 0, 0], [4, 9, 14, 19, 24]]

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  low_pass_alpha: 0.2

right:
  type: DexPilot
  urdf_path: urdf/inspire_right_hand.urdf
  wrist_link_name: "R_hand_base_link"

  finger_tip_link_names:
    ["R_thumb_tip", "R_index_tip", "R_middle_tip", "R_ring_tip", "R_pinky_tip"]


  target_joint_names:
    [
      "R_pinky_proximal_joint",
      "R_ring_proximal_joint",
      "R_middle_proximal_joint",
      "R_index_proximal_joint",
      "R_thumb_proximal_pitch_joint",
      "R_thumb_proximal_yaw_joint",
    ]
  scaling_factor: 0.85
  # target_link_human_indices: [[0, 0, 0, 0, 0], [4, 9, 14, 19, 24]]
  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  low_pass_alpha: 0.2
