defaults:
  - teleop
  - override hand: fourier_dexpilot_dhx
  - override robot: ??? # e.g. "robot: 'gr1t2'"
  - override camera: ??? # e.g. "camera: 'oak_97'"
  - _self_

debug: false
debug_hand: false
sim: false
wait_time: 3.0
frequency: 60
use_waist: false
use_head: false
use_depth: false
task_name: ??? # e.g. "task_name: 'task_name'"

gravity_compensation: false

cpu:
  affinity: []
  niceness: -15

recording:
  enabled: true
  task_name: ${task_name}
  operator: -1
  pilot: -1

upsampler:
  frequency: 250
  gravity_compensation: ${gravity_compensation}
