defaults:
  - _self_

  - hand: fourier_dexpilot
  - robot: "gr1t1_legacy"
  - camera: oak_97
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog


debug: false
debug_hand: false
sim: false
wait_time: 5.0
frequency: 30
use_waist: false
use_head: false
use_depth: true

cpu:
  affinity: []
  niceness: -5

recording:
  enabled: false
  task_name: "eval"

joint_filter:
  min_cutoff: 0.01
  beta: 10.0

hand_filter:
  min_cutoff: 0.001
  beta: 50.0

head_filter:
  alpha: 0.7

upsampler:
  frequency: 120
  gravity_compensation: false

hydra:
  job:
    chdir: false
  run:
    dir: outputs/pick_place/${now:%Y-%m-%d_%H-%M-%S}

camera:
  instance:
    eval_mode: true

robot:
  policy:
    repo_id: "pick_place"
    type: "idp3"
    pretrained_path: ???

    config:
      n_action_steps: 15
      # center_crop: true

eval:
  # rerun_endpoint: 192.168.31.184:9876
  states:
    qpos: [0, 20]
    hand_qpos: [20, 32]
  actions:
    qpos: [0, 20]
    hand_qpos: [20, 32]
  cameras:
    top:
      streams: ["rgbd"]
