defaults:
  - hand: fourier_dexpilot_dhx
  - robot: "gr1t1_legacy"
  - camera: oak_97
  - policy: ???

  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# robot:
#   urdf_path: "urdf/GR1T2_inspire_hand.urdf"
# hand:
#   left:
#     urdf_path: urdf/fourier_hand_left.urdf
#   right:
#     urdf_path: urdf/fourier_hand_right.urdf

debug: false
debug_hand: false
sim: false
wait_time: 5.0
frequency: 30
use_waist: false
use_head: false
use_depth: true

cpu:
  affinity: []
  niceness: -5

recording:
  enabled: false
  task_name: "eval"

joint_filter:
  min_cutoff: 0.01
  beta: 10.0

hand_filter:
  min_cutoff: 0.001
  beta: 50.0

head_filter:
  alpha: 0.7

upsampler:
  frequency: 120
  gravity_compensation: false

hydra:
  job:
    chdir: false
  run:
    dir: outputs/${policy.instance.policy_type}-${now:%Y-%m-%d_%H-%M-%S}
  verbose: [teleoperation, __main__]

camera:
  instance:
    eval_mode: true

eval:
  prompt: "Pick up the lemon and put it in the basket"
  rerun_enabled: false
  rerun_endpoint: 192.168.31.184:9876

  display_keys:
    states:
      ["waist", "neck", "left_arm", "right_arm", "left_hand", "right_hand"]
    actions:
      ["waist", "neck", "left_arm", "right_arm", "left_hand", "right_hand"]

  modality_mask:
    states: ["left_leg", "right_leg", "waist", "neck"]
    actions: ["left_leg", "right_leg", "waist", "neck"]

  cameras:
    observation.images.top:
      stream: rgb
      name: top
