defaults:
  - teleop
  - override hand: fourier_dexpilot_dhx
  - override robot: gr1t2_legacy
  - override camera: zed
  - _self_


debug: false
debug_hand: false
sim: false
wait_time: 3.0
frequency: 60
use_waist: false
use_head: false
