defaults:
  - teleop
  - override hand: fourier_12dof_dexpilot
  - override robot: gr1t2
  - override camera: oak
  - _self_

robot:
  urdf_name: "gr1t2_fourier_hand_12dof"

debug: false
debug_hand: false
sim: false
wait_time: 3.0
frequency: 60
use_waist: false
use_head: false
