from collections.abc import Sequence
from typing import Protocol, runtime_checkable


@runtime_checkable
class Hand(Protocol):
    def init(self): ...
    def get_positions(self) -> Sequence[int]: ...
    def set_positions(self, positions: Sequence[int]): ...
    def reset(self): ...
