from typing import Protocol, runtime_checkable


@runtime_checkable
class RobotAdapter(Protocol):
    @property
    def joint_positions(self): ...

    def connect(self): ...

    def disconnect(self): ...

    def command_joints(self, joint_positions, gravity_compensation=False): ...

    def init_command_joints(self, positions): ...

    def stop_joints(self): ...

    def observe(self) -> tuple: ...
